apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: myk8sapp
  name: myk8sapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myk8sapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myk8sapp
    spec:
      containers:
      - image: rakibhasansazib/test:17
        name: myk8sapp
        resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
spec:
  type: NodePort
  selector:
    app: myk8sapp
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30007
